### ISSUE TITLE
room_temp_api_timeout not working

### ISSUE THREAD

**Issue by th3sniper86** [ginkage/MHI-AC-Ctrl-ESPHome#103]
I’m using an external temperature sensor to set the current room temperature using the service ‘set_api_room_temperature’. This works, but after one minute, the temperature is set back to the internal temperature sensor, despite the timeout has not passed.

![IMG_0034](https://github.com/user-attachments/assets/3a7b4c7c-c37b-40b4-9345-a885fe0ae65d)

Tested with AC off and in heating mode with:

globals:
  - id: room_temp_api_timeout
    type: int
    restore_value: no
    initial_value: "1800"

**Comment by serrj-sv** [comment]
```
MhiAcCtrl:
  id: ${mhi_device_id}
  frame_size: ${frame_size}
  room_temp_timeout: 1800
```
