### ISSUE TITLE
Feature Request // -- Allow "float temperature_step_ { 1.0f };" Option via yaml

### ISSUE THREAD

**Issue by EvoSems** [ginkage/MHI-AC-Ctrl-ESPHome#111]
Just updated to 3.0! wooo.

I prefer the 1.0 stepping vs 0.5 which I could easily edit pre 3.0.

would it be possible to make this a feature and allow this through the yaml some how?

many thanks

**Comment by backyardaussie** [comment]
change your esphome yaml code in the climate section

```
climate:
  - platform: MhiAcCtrl
    mhi_ac_ctrl_id: ${mhi_device_id}
    id: ${deviceid}
    name: "${devicename}"
    visual:
      temperature_step: 1.0
```
