### ISSUE TITLE
ESP32S3 - ATOM S3 lite

### ISSUE THREAD

**Issue by fonske** [ginkage/MHI-AC-Ctrl-ESPHome#112]
Hi All,

Not an issue, but to let know, i have made a new pcb with a M5stack Atom S3 lite instead of the Wemos D1 mini.
It is a bit faster and dual core, so bluetooth and wifi should be possible at the same time.
Also the atom has the possibility to have an extra sensor connected from M5stack, like the ENV IV, CO2, ENV pro, KMeter-iso thermocouple.
I used a few sensors and programmed them in the forked repo, in the atom branch.
https://github.com/fonske/MHI-AC-Ctrl-ESPHome/tree/atom
In the map photos there are some photos of the pcb.

If the sensor contains external temperature, it can be used to control the MHI. Its programmed in the sensor yaml.

@ginkage Can i merge this branch with your github repo? Thank you.

![4](https://github.com/user-attachments/assets/7566cd5b-9c02-4b55-b575-643c147ba74a)

**Comment by EvoSems** [comment]
Hi. very cool. keen to build! I have sent you an email. thanks

**Comment by HpNoTiQ56** [comment]
Hi,
You deleted branch recently but I tried to use it with another esp32 but got a lot of loop error -2 even changing time for loop in program. Why did you deleted it? Too many errors or no use?

**Comment by HpNoTiQ56** [comment]
Thank you!. How did you manage to get ride of the anoying loop on ESP32 (A/C are working great using esp8266). I'm using D1 MINI ESP3 using legacy board + redifining pins but log is flooded with loop error even when trying to increase loop timeout. I don't want webserver only bluetooth proxy!
I don't care about loop errors but sometimes the A/C doesn't execute the command sent over HA.

**Comment by rhvs** [comment]
A bit late, but I managed to get to a working yaml with a bit of Astute and a bit of Claude... please find the code below with all the comments by Claude left in. My hardware is the M5stack/S3 based solution from @fonske 

```

# =====================================================================
# MHI-AC-Ctrl  —  Guest Room AC (ac-3)
# Migrated from fonske/atom  ->  Astute4185 (ESP-IDF, native components)
# Board: M5Stack ATOM S3 (Lite)
#
# SPI pins below match the fonske ATOM S3 PCB wiring (SCK=8, MOSI=38,
# MISO=39). Do NOT use the 14/13/12 from the upstream example.
#
# Secrets used (already in your setup): ota_password_ac3,
# wifi_ssid, wifi_password
# =====================================================================

substitutions:
  device_name: "ac-3"
  friendly_name: "Guest Room AC"
  # frame_size 33 = 3D Auto + left/right vanes work.
  # Switch to 20 ONLY if you get checksum / loop error: -2 problems.
  frame_size: "33"

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  min_version: 2026.3.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf          # now the default for ESP32-S3; Astute4185 requires it

logger:
  level: INFO              # was DEBUG; INFO reduces blocking that can trigger loop -2

ota:
  - platform: esphome
    password: !secret ota_password_ac3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  min_auth_mode: WPA2
  # Fallback hotspot (captive portal) if wifi fails
  ap:
    ssid: ${friendly_name}
    ap_timeout: 30s
    password: "configesp"

captive_portal:

improv_serial:

external_components:
  - source: github://Astute4185/MHI-AC-Ctrl-ESPHome_ESP-IDF@master
    components: [MhiAcCtrl]
    refresh: 0s         # force a fresh clone; relax to e.g. 1d once it compiles

# Home Assistant API
api:
  reboot_timeout: 0s
  # To enable encryption: add api_encryption_key to secrets.yaml and uncomment
  #encryption:
  #  key: !secret api_encryption_key
  services:
    # Push an external room temperature from HA (falls back to internal
    # sensor after room_temp_timeout seconds without an update)
    - service: set_external_room_temperature
      variables:
        temperature_value: float
      then:
        - climate.mhi.set_external_room_temperature:
            temperature: !lambda "return temperature_value;"

MhiAcCtrl:
  frame_size: ${frame_size}
  # --- ATOM S3 (fonske PCB) SPI wiring -- leave as-is for your hardware ---
  sck_pin: 8
  mosi_pin: 38
  miso_pin: 39
  initial_vertical_vanes_position: 5
  initial_horizontal_vanes_position: 8
  room_temp_timeout: 60

button:
  - platform: restart
    name: "Restart"
    entity_category: diagnostic
    icon: mdi:restart

climate:
  - platform: MhiAcCtrl
    name: "Climate"
    temperature_offset: true
    visual_min_temperature: 17.0
    visual:
      temperature_step:
        target_temperature: 0.5
        current_temperature: 0.1

time:
  - platform: homeassistant
    id: homeassistant_time

binary_sensor:
  - platform: MhiAcCtrl
    defrost:
      name: "Defrost"
    vanes_3d_auto_enabled:
      name: "3D Auto Enabled"
  - platform: status
    name: "Status"
    entity_category: diagnostic

sensor:
  - platform: uptime
    name: "Uptime"
    entity_category: diagnostic
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    entity_category: diagnostic
  - platform: MhiAcCtrl
    outdoor_temperature:
      name: "Outdoor Temperature"
    return_air_temperature:
      name: "Return Air Temperature"
    outdoor_unit_fan_speed:
      name: "Outdoor Unit Fan Speed"
    indoor_unit_fan_speed:
      name: "Indoor Unit Fan Speed"
    compressor_frequency:
      name: "Compressor Frequency"
    indoor_unit_total_run_time:
      name: "Indoor Unit Total Run Time"
    compressor_total_run_time:
      name: "Compressor Total Run Time"
    current_power:
      name: "Current Power"
    energy_used:
      name: "Energy Used"
    indoor_unit_thi_r1:
      name: "Indoor HE Temp 1"
    indoor_unit_thi_r2:
      name: "Indoor HE Temp 2"
    indoor_unit_thi_r3:
      name: "Indoor HE Temp 3"
    outdoor_unit_tho_r1:
      name: "Outdoor HE Temp"
    outdoor_unit_expansion_valve:
      name: "Outdoor Unit Expansion Valve"
    outdoor_unit_discharge_pipe:
      name: "Outdoor Unit Discharge Pipe"
    outdoor_unit_discharge_pipe_super_heat:
      name: "Outdoor Unit Discharge Pipe Super Heat"
    protection_state_number:
      name: "Compressor Protection Code"
    error_code:
      name: "Error Code"
    vanes_pos:
      name: "Vanes"
    vanesLR_pos:
      name: "Vanes Left-Right"

text_sensor:
  - platform: version
    name: "ESPHome Version"
    entity_category: diagnostic
  - platform: MhiAcCtrl
    protection_state:
      name: "Compressor Protection Status"

select:
  - platform: MhiAcCtrl
    vertical_vanes:
      name: "Vanes Up-Down"
    horizontal_vanes:
      name: "Vanes Left-Right"
    fan_speed:
      name: "Fan Speed"

switch:
  - platform: MhiAcCtrl
    vanes_3d_auto:
      name: "3D Auto"

```
