### ISSUE TITLE
Problem with yaml insertion in V2.0

### ISSUE THREAD

**Issue by Bill-Dung** [ginkage/MHI-AC-Ctrl-ESPHome#86]
Compiling V2.0 stops with the following message:

```
Compiling .pioenvs/wz-mhi-ac/src/main.cpp.o
In file included from src/main.cpp:94:
src/mhi_ac_ctrl.h: In member function 'virtual void MhiAcCtrl::setup()':
src/mhi_ac_ctrl.h:128:44: error: 'frame_size' was not declared in this scope
  128 |         mhi_ac_ctrl_core.set_frame_size(id(frame_size)); // set framesize. Only 20 (legacy) or 33 (includes 3D auto and vertical vanes) possible
      |                                            ^~~~~~~~~~
Generating LD script .pioenvs/wz-mhi-ac/ld/local.eagle.app.v6.common.ld
Compiling .pioenvs/wz-mhi-ac/lib61b/ESPAsyncTCP-esphome/AsyncPrinter.cpp.o
*** [.pioenvs/wz-mhi-ac/src/main.cpp.o] Error 1
========================= [FAILED] Took 39.15 seconds =========================

```
It looks like the yaml insertion of the frame files doesn't work. I have three A/Cs because of this i put all files accept the lr_mhi_ac_ctrl.yaml into a subfolder and renamed the lr_mhi_ac_crtrl.yaml for each A/C. The includes from the subfolder are working fine only the insertion obviously not. That's how it looks like:

```
esphome:
  name: wz-mhi-ac
  friendly_name: Klimaanlage Wohnzimmer
  platform: ESP8266
  board: d1_mini
  platformio_options:
    # Run CPU at 160Mhz to fix mhi_ac_ctrl_core.loop error: -2
    board_build.f_cpu: 160000000L
  includes:
    - MHI-AC-CTRL-ESPHome/mhi_ac_ctrl.h
    - MHI-AC-CTRL-ESPHome/MHI-AC-Ctrl-core.h
    - MHI-AC-CTRL-ESPHome/MHI-AC-Ctrl-core.cpp


# Enable this for current units, supporting the larger framesize
# Comment if you encounter mhi_ac_ctrl_core.loop error: -2 errors and uncomment the legacy_framesize file
<<: !include MHI-AC-CTRL-ESPHome/conf/large_framesize.yaml
# Uncomment this to allow for a working configuration on floor units or older units
# <<: !include conf/legacy_framesize.yaml
```
  
Any ideas? If you need more information please ask. And sorry about my poor English.
