### ISSUE TITLE
Adding wireless remote temperature reading

### ISSUE THREAD

**Issue by persistive** [ginkage/MHI-AC-Ctrl-ESPHome#92]
At this moment two possibilities for room temperature readings are possible: internal temperature and an external wired sensor.
I would like to use a temperature reading connected wireless to HA as the room temperature.
I presume this should be possible but before i damage something in the software i would appriciate some help with this.
Thanks in advance,

Paul

**Comment by scottg88** [comment]
Hey Paul, conveniently this is precisely the reason for the HA service call which is surfaced by the device in the ESPHome YAML called `set_api_room_temperature`:

https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/blob/master/lr_mhi_ac_ctrl.yaml#L50

It shows up as `esphome.<ac_name>_set_api_room_temperature` in Home Assistant when calling a service in an automation.

Like the comment the YAML says, you need to ensure you publish the value (whether it's changed or not) at a higher frequency than `room_temp_api_timeout` seconds, which [by default is `120` seconds](https://github.com/ginkage/MHI-AC-Ctrl-ESPHome/blob/master/conf/large_framesize.yaml#L6). This means more often than every 2 minutes. I chose to do it every 1 minute. If you don't do it in time, the temperature will fall back to the internal sensor automatically (which would cause weird behaviour if the AC kept swapping temperatures between the two).

Here's an example HA automation for you using a temperature sensor state:

```
alias: Set Room Temps
description: ""
trigger:
  - platform: time_pattern
    seconds: "0"
condition: []
action:
  - service: esphome.example_ac_set_api_room_temperature
    data:
      value: "{{ states('sensor.example_temperature') }}"
mode: single
```
